apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-volume
  labels:
    type: wordpress
    tier: frontend
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nfs/var/nfsshare/wordpress/html"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: wordpress
    tier: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nfs/var/nfsshare/wordpress/mysql"

